name: Compile and deploy website to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/deploy-pages.yml"
      - "www/**"
      - "discord-css/**"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Run sh build script
        run: bash ./www/build.sh "${{ secrets.SECRET_KEY }}" "${{ secrets.SECRET_IV }}"

      - name: Run py build script
        run: python3 "www/build.py" "${{ github.repository }}" "${{ github.sha }}" "${{ github.token }}"

      - name: Compress & Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./www" # Website root

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
