name: Do something with repo file structure

on:
  push:
    paths: [".github/workflows/do-something-with-repo-tree.yml"]
  workflow_dispatch:

jobs:
  something:
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch repo tree
        run: curl -o tree.json "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/git/trees/${{ github.sha }}"
      - name: Fetch repo tree (recursive)
        run: curl -o tree-recursive.json "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/git/trees/${{ github.sha }}?recursive=1"

      - name: Do something with tree
        uses: actions/upload-artifact@v4
        with:
          path: "tree*.json"
          name: tree
          if-no-files-found: error
