name: List repo object types

on:
  push:
    paths:
      - ".github/workflows/do-something-with-repo-tree.yml"
      - "treeing.py"
  workflow_dispatch:

jobs:
  get-tree-lists:
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch repo tree (root)
        run: |
          curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" -Lo tree-root.json --fail-with-body "https://api.github.com/repos/${{ github.repository }}/git/trees/${{ github.sha }}"
          echo "========"
          cat tree-root.json
      - name: Fetch repo tree (recursive)
        run: |
          curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" -Lo tree-recursive.json --fail-with-body "https://api.github.com/repos/${{ github.repository }}/git/trees/${{ github.sha }}?recursive=1"
          echo "========"
          cat tree-recursive.json

      - name: Upload tree files
        uses: actions/upload-artifact@v4
        with:
          path: "tree*.json"
          name: tree
          if-no-files-found: error

  list-object-types:
    needs: get-tree-lists
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download tree lists
        uses: actions/download-artifact@v4
        with:
          name: tree

      - name: Object types in repository root
        run: python3 "treeing.py" "tree-root.json"
      - name: Object types in repository (recursive)
        run: python3 "treeing.py" "tree-recursive.json"
