name: Do nothing with repo file structure

on:
  push:
    paths:
      - ".github/workflows/do-something-with-repo-tree.yml"
      - "treeing.py"
  workflow_dispatch:

jobs:
  nothing:
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch repo tree
        run: curl -o tree.json "https://api.github.com/repos/${{ github.repository }}/git/trees/${{ github.sha }}"
      - name: Fetch repo tree (recursive)
        run: curl -o tree-recursive.json "https://api.github.com/repos/${{ github.repository }}/git/trees/${{ github.sha }}?recursive=1"

      - name: Upload tree files
        uses: actions/upload-artifact@v4
        with:
          path: "tree*.json"
          name: tree
          if-no-files-found: error

  something:
    needs: nothing
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download tree files
        uses: actions/download-artifact@v4
        with:
          name: tree

      - name: Do something?
        run: python3 "treeing.py" "tree.json"
      - name: Do something MORE!
        run: python3 "treeing.py" "tree-recursive.json"
