name: List repository files (very useful information)

on:
  push:
    branches: ["main"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: tree -sno tree.txt --du
      - uses: actions/upload-artifact@v4
        with:
          path: tree.txt
