name: List repository files (actually useful information, believe it or not)

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: tree -sno tree.txt --du
      - uses: actions/upload-artifact@v4
        with:
          path: tree.txt
          name: tree
