on:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Change directory
        run: cd vscode-rufo
      - name: Print working directory and list its contents
        run: |
          echo $PWD
          ls -lah
      - name: Install dependencies
        run: npm i
      - name: Run pre-test script
        run: npm run pretest
      - name: Run tests
        run: npm run test
