on:
  push:
    paths: [.github/workflows/run-extension-tests.yml, vscode-rufo]
  workflow_call:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "vscode-rufo"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install npm dependencies
        run: npm i
      - name: Install other dependencies
        run: |
          sudo apt update
          sudo apt install xvfb ruby -y
          sudo gem install rufo
      - name: Run tests
        run: |
          Xvfb :99 &
          export DISPLAY=:99
          npm run test

  windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: "vscode-rufo"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install npm dependencies
        run: npm i
      - name: Install other dependencies
        run: |
          curl -Lo ruby.exe https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.3.5-1/rubyinstaller-devkit-3.3.5-1-x64.exe
          .\ruby.exe
          gem install rufo
      - name: Run tests
        run: npm run test
