on:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "vscode-rufo"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Print working directory and list its contents
        run: |
          echo $PWD
          ls -lah
      - name: Install npm dependencies
        run: npm i
      - name: Install other dependencies
        run: apt install xorg-server xorg-xinit
      - name: Run tests
        run: |
          startx &
          npm run test
          kill %1
