name: Deploy TypeScript website to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Build TypeScript
        run: tsc -p "./www/tsconfig.json"
      - name: Prepare GET server
        run: curl "https://ifconfig.me/ip" -o "./www/ip.txt"
      - name: Run custom build script
        run: python3 "www/build.py" "${{ secrets.SECRET_STRING }}"

      - name: Compress & Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./www" # Website root

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Run GET server
        run: python3 "www/server.py" "${{ secrets.SECRET_STRING }}" 60
